import type { Metadata } from "next";
import "./globals.css";
// Ajoute cette ligne ci-dessous :
import { Geist, Geist_Mono } from "next/font/google"; 
import { Toaster } from "react-hot-toast";
// Maintenant, ces fonctions sont définies grâce à l'import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Toaster />
        <div className="flex justify-center items-center min-h-screen my-5">
            {children}
        </div>
      </body>
    </html>
  );
}